name: flutter_getx_base
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.0.3
  get: ^4.6.1
  dio: ^4.0.6
  graphql: ^5.1.1
  equatable: ^2.0.5
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  flutter_easyloading: ^3.0.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - environments/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400